### ISSUE TITLE
Cannot reopen the About window on Mac

### ISSUE THREAD

**Issue by majaode** [fabiospampinato/electron-about#1]
How to reproduce:

- Click about menu
- Close about window
- Click about menu again

Here is the error log
```
Uncaught Exception:
TypeError: Object has been destroyed
    at Object.focus ([path_removed]/node_modules/electron-about/dist/index.js:13:17)
    at Object.open ([path_removed]/node_modules/electron-about/dist/index.js:59:19)
    at click ([path_removed]/node_modules/electron-about/dist/index.js:79:23)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13)
```

Note: [path_removed] for privacy

**Comment by fabiospampinato** [comment]
Give me a few days 👍

**Comment by fabiospampinato** [comment]
Fixed, thanks a lot for reporting the issue!
